[NCL-8132] Specify new roles for Rex
project-ncl/rex pull request #55
Opened 2023-08-10 20:21 UTC by thescouser89

With the authorization initiative, we need to restrict who can access Rex. With that in mind, we'll allow users with roles:

- pnc-users-rex-admin (mostly service accounts)
- pnc-users-admin (human PNC developers)

to interact with Rex.

This is needed as we also start using a unique service account for Rex (NCL-8054) to trigger the task endpoints. That service account might have special roles which not all users should be able to indirectly invoke.

2023-08-22 10:46 UTC, michalovjan requested changes
I have couple caveats. 

1. Why is there a 'users' part in the roles?
2. _pnc-admin_ seems less confusing for us as admins
3. I don't like that RHPAM will be basically global admin for every endpoint. There should be a differentiation for 'user' endpoints which RHPAM uses and admin endpoints which should be privileged. For example the InternalEndpoint.setConcurrent endpoint should be available to JUST admin and should have higher rights. This endpoint will most likely be called by Orch, so Orch should be able to call it but RHPAM shouldn't.

2023-08-22 15:38 UTC, thescouser89 commented
Hi,

1. I added the 'pnc-users-' prefix to avoid collisions with any other groups in Rover groups. We know that this is PNC app specific.
2. Similarish answer to 1.
3. Sure! Could you provide me a list of endpoints which only admins can do and other endpoints which any authenticated user can access? I'll adjust accordingly. Could you also provide me with the different admin roles required and the associated endpoints please?

2023-08-23 10:56 UTC, michalovjan commented
Can we change it to like pnc-app-user and pnc-app-admin? Like 2 roles, which could be shared? Orch would be *-admin and *-user, whilst RHPAM just *-user. Or should we go more granular per-app like pnc-app-rex-user and such. 

For the pnc-users-* prefix, I think the pnc-users-* is confusing as a role because to me, it sounds like an admin to users. 

Additionally, I don't understand the need for 2 seperate admin roles, is that there because we don't want regular users to be able to invoke Rex? That could be solved by per-app roles. Right now, with 2 *-admin roles, it sounds like you have to be an admin to be able to do anything in Rex.

2023-08-23 14:24 UTC, thescouser89 commented
```
Can we change it to like pnc-app-user and pnc-app-admin? Like 2 roles, which could be shared? Orch would be *-admin and *-user, whilst RHPAM just *-user. Or should we go more granular per-app like pnc-app-rex-user and such.
```
I'm unsure about the role per service account. To access a certain endpoint, the user would need a particular role. So both service accounts will then get that particular role. It's more like:
- a particular endpoint(s) can be accessed by some users, so we create a role for it and verify that the user has that role
- rather than a per-app permission to access the endpoints.

```For the pnc-users-* prefix, I think the pnc-users-* is confusing as a role because to me, it sounds like an admin to users.```
At this point this change will be problematic because this has already been applied to other applications :(
If the other team members have a strong opinion to change it, I'll do it but I'll have to change it on other apps.

There's an MVP on Confluence that I'll send you to post comments on the naming.

```Additionally, I don't understand the need for 2 seperate admin roles, is that there because we don't want regular users to be able to invoke Rex? That could be solved by per-app roles. Right now, with 2 *-admin roles, it sounds like you have to be an admin to be able to do anything in Rex.```

One admin role (pnc-users-admin) is for the humans (us) that has access to all the endpoints (not just for Rex, but also for other services). The other role (pnc-users-rex-admin) is only assigned to service accounts and/or users who really need to access Rex endpoints.

We also do not want regular users to invoke Rex, because Rex will use a service account with special roles assigned to it. It is the principal of least privileges as suggested by Prod security.

I hope I answered your questions but let me know if this is still confusing!

2023-08-23 15:22 UTC, michalovjan requested changes

2023-08-23 15:22 UTC, michalovjan commented on core/src/main/java/org/jboss/pnc/rex/rest/InternalEndpointImpl.java
> +    @RolesAllowed({ "pnc-users-rex-admin", "pnc-users-admin" })
Leaving out the naming: `"pnc-users-rex-admin", "pnc-users-rex-user", "pnc-users-admin"`

2023-08-23 15:22 UTC, michalovjan commented on core/src/main/java/org/jboss/pnc/rex/rest/InternalEndpointImpl.java
> +    @RolesAllowed({ "pnc-users-rex-admin", "pnc-users-admin" })
Leaving out the naming: `"pnc-users-rex-admin", "pnc-users-rex-user", "pnc-users-admin"`

2023-08-23 15:22 UTC, michalovjan commented on core/src/test/java/org/jboss/pnc/rex/core/authentication/AuthenticationTest.java
> +                .auth().oauth2(getAccessToken("alice", Set.of("pnc-users-rex-admin")))
pnc-users-rex-user

2023-08-24 14:28 UTC, thescouser89 commented on core/src/main/java/org/jboss/pnc/rex/rest/InternalEndpointImpl.java
>      public void setConcurrent(Long amount) {
Did you mean to add something else for this one @michalovjan ?

2023-08-28 15:56 UTC, michalovjan approved these changes

2023-09-08 14:34 UTC, merged