[NCL-8054] Use service account when for start and stop job
project-ncl/rex pull request #56
Opened 2023-08-10 21:13 UTC by thescouser89

This is required since the user shouldn't be sending access token HTTP headers in the original request; that access token will expire quickly.

Instead, we can use our own service account to add fresh HTTP authorization header.

2023-08-22 13:34 UTC, michalovjan requested changes

2023-08-22 13:34 UTC, michalovjan commented on core/src/main/java/org/jboss/pnc/rex/core/RemoteEntityClient.java
> +    private List<Header> addAuthenticatedHeaderToHeaders(List<Header> headers) {
what if the Authorization header is already present? should we overwrite it or prefer it?

2023-08-23 09:40 UTC, michalovjan approved these changes

2023-08-23 17:38 UTC, thescouser89 commented
Thanks @michalovjan for the review! I'll merge it when I have the service account setup.

2023-08-29 15:38 UTC, merged