[NCL-8970] Implement Rex rest client
project-ncl/rex pull request #92
Opened 2024-12-09 13:15 UTC by jomrazek

2024-12-12 21:15 UTC, thescouser89 commented
How can we use the rex client? Is it generated from the openapi?

2024-12-12 21:38 UTC, jomrazek commented
@thescouser89 yup generated with quarkus openapi client generator, usage here at the end of the chapter https://docs.quarkiverse.io/quarkus-openapi-generator/dev/client.html#getting-started

2024-12-16 12:53 UTC, michalovjan requested changes
Looks fine to me! Can it ignore some classes and use them directly? For example Request.class from pnc-api jar. It'd be great to be able to use that one directly. 

We can merge this and if there are any usage issues, f.e. with auth token we can create new PR. Thanks for your work on this @jomrazek! :)

2024-12-17 18:35 UTC, thescouser89 commented
retest this please

2024-12-19 20:24 UTC, thescouser89 commented
I tried it in a test app and the `TaskEndpointApi` doesn't work as intended.

```java
TaskSetResponse response = taskEndpointApi.getAll(false, null, null);
```

Unfortunately, the `getAll` JSON is just an array, and Jackson cannot map it to `TaskSetResponse`:
```java
public class TaskSetResponse {
    private Set<TaskDTO> taskDTOS;
    ...
}
```
since that would require a map rather than a array.

# Reproducer
https://github.com/thescouser89/rexclientest
(Update `src/main/resources/application.properties` with the Rex url)

# Other issues found in my test Quarkus project
1. I had to exclude the quarkus-rest-client-reactive-jackson and quarkus-rest-client-reactive dependencies since they'll clash with my Quarkus version rest-client-jackson dependency.
2. The configuration key of the rex client is 'openapi_yaml'. Could we customize this to something more descriptive like 'rexclient' ?

2025-01-14 16:20 UTC, michalovjan approved these changes

2025-01-15 11:32 UTC, michalovjan approved these changes

2025-01-15 11:34 UTC, merged